### ISSUE TITLE
Add an example to README

### ISSUE THREAD

**Issue by mirelon** [bootstrap-ruby/rails-bootstrap-navbar#13]
README is just referring to bootstrap-navbar. But there is an example which is not usable, because some of the methods are overriden in NavbarHelper (e.g. brand_link has 3 parameters instead of 2)

**Comment by manuelmeurer** [comment]
Hmm, not sure what you mean. This gem doesn't add any functionality nor does it override anything. I'm also not sure which `NavbarHelper` you refer to and to my knowledge, there is no `brand_link` method anywhere. Could you elaborate?

**Comment by mirelon** [comment]
I am sorry, it was just conflict of nav
